<?php declare(strict_types=1);
namespace App\Services;
use App\Repositories\SettingsRepository;
final class SettingsService {
    private ?array $values=null;
    public function __construct(private SettingsRepository $settings, private LogService $log) {}
    public function all(): array { return $this->values ??= array_replace(['ffmpeg_path'=>config('ffmpeg.path'),'ytdlp_path'=>config('youtube.ytdlp_path'),'default_resolution'=>config('stream.default_resolution'),'default_bitrate'=>config('stream.default_bitrate'),'auto_restart'=>(string)(int)config('stream.auto_restart'),'timezone'=>config('app.timezone'),'theme'=>'light'],$this->settings->all()); }
    public function save(array $input): void { $resolution=trim((string)($input['default_resolution']??''));$bitrate=trim((string)($input['default_bitrate']??''));$timezone=trim((string)($input['timezone']??''));if(!preg_match('/^\d{2,4}x\d{2,4}$/',$resolution))throw new \InvalidArgumentException('Resolution must look like 1280x720.');if(!preg_match('/^\d{2,5}k$/i',$bitrate))throw new \InvalidArgumentException('Bitrate must look like 2500k.');if(!in_array($timezone,timezone_identifiers_list(),true))throw new \InvalidArgumentException('Timezone is invalid.');foreach(['ffmpeg_path','ytdlp_path'] as $pathKey){$path=trim((string)($input[$pathKey]??''));if($path===''||$path[0]!=='/')throw new \InvalidArgumentException('Executable paths must be absolute.');$this->settings->save($pathKey,$path);} foreach(['default_resolution','default_bitrate','timezone'] as $key)$this->settings->save($key,trim((string)$input[$key]));$this->settings->save('theme',($input['theme']??'light')==='dark'?'dark':'light');$this->settings->save('auto_restart',isset($input['auto_restart'])?'1':'0'); $this->values=null; $this->log->info('Settings updated'); }
}
