<?php declare(strict_types=1);
namespace App\Services;
use App\Constants\StreamStatus;use App\Repositories\{ChannelRepository,PlaylistRepository,StreamRepository};
final class StreamService {
    public function __construct(private StreamRepository $streams,private ChannelRepository $channels,private PlaylistRepository $playlists,private SettingsService $settings,private StreamLifecycleService $lifecycle,private LogService $log){}
    public function active():?array{return $this->streams->active();} public function latest():?array{return $this->streams->latest();}
    public function start(int $channelId,int $playlistId,?string $start,?string $end):int { if($this->streams->active())throw new \LogicException('Another stream is already active.');if(!$this->channels->find($channelId))throw new \InvalidArgumentException('Channel not found.');if(!$this->playlists->find($playlistId)||!$this->playlists->videos($playlistId))throw new \InvalidArgumentException('Playlist must contain at least one video.');$startUtc=$this->toUtc($start);$endUtc=$this->toUtc($end);if($endUtc&&$startUtc&&strtotime($endUtc)<=strtotime($startUtc))throw new \InvalidArgumentException('End time must be after start time.');$id=$this->streams->create($channelId,$playlistId,$startUtc,$endUtc);$this->log->info('Stream queued',['stream_id'=>$id,'channel_id'=>$channelId,'playlist_id'=>$playlistId]);return $id; }
    public function stop(int $id):void{$stream=$this->require($id);if(in_array($stream['status'],[StreamStatus::QUEUED,StreamStatus::STARTING,StreamStatus::RUNNING,StreamStatus::RESTARTING],true))$this->lifecycle->transition($stream,StreamStatus::STOPPING,['stop_requested'=>1]);$this->log->info('Stop requested',['stream_id'=>$id]);}
    public function restart(int $id):void{$stream=$this->require($id);if($stream['status']!==StreamStatus::RUNNING)throw new \LogicException('Only a running stream can be restarted.');$this->streams->update($id,['restart_requested'=>1]);$this->log->info('Restart requested',['stream_id'=>$id]);}
    public function displayDate(?string $utc):?string {if(!$utc)return null;return (new \DateTimeImmutable($utc,new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone($this->settings->all()['timezone']))->format('Y-m-d H:i:s T');}
    private function toUtc(?string $local):?string {if(!$local)return null;$zone=new \DateTimeZone($this->settings->all()['timezone']);return (new \DateTimeImmutable($local,$zone))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');}
    private function require(int $id):array{$stream=$this->streams->find($id);if(!$stream)throw new \InvalidArgumentException('Stream not found.');return $stream;}
}
