<?php declare(strict_types=1);
use App\Controllers\{AuthController,DashboardController,ManageController};
use App\Http\Router;
use App\Infrastructure\Container;
require dirname(__DIR__).'/vendor/autoload.php';
require dirname(__DIR__).'/app/Helpers/functions.php';
date_default_timezone_set(config('app.timezone'));
session_name(config('app.session_name'));
session_set_cookie_params(['httponly'=>true,'secure'=>(($_SERVER['HTTPS']??'')==='on'),'samesite'=>'Lax']);
session_start();
$_SESSION['csrf'] ??= bin2hex(random_bytes(32));
set_exception_handler(function(Throwable $e): void { error_log((string)$e); http_response_code(500); echo config('app.debug')?e($e->getMessage()):'An unexpected error occurred.'; });
$container=new Container();$router=new Router($container);
$router->add('GET','/login',[AuthController::class,'login'],false);
$router->add('POST','/login',[AuthController::class,'authenticate'],false);
$router->add('POST','/logout',[AuthController::class,'logout']);
$router->add('GET','/',[DashboardController::class,'index']);
$router->add('GET','/api/health',[DashboardController::class,'health']);
$router->add('GET','/channels',[ManageController::class,'channels']);
$router->add('POST','/channels',[ManageController::class,'createChannel']);
$router->add('POST','/channels/update',[ManageController::class,'updateChannel']);
$router->add('POST','/channels/delete',[ManageController::class,'deleteChannel']);
$router->add('GET','/videos',[ManageController::class,'videos']);
$router->add('POST','/videos/upload',[ManageController::class,'upload']);
$router->add('POST','/videos/delete',[ManageController::class,'deleteVideo']);
$router->add('POST','/videos/import',[ManageController::class,'import']);
$router->add('GET','/playlists',[ManageController::class,'playlists']);
$router->add('POST','/playlists',[ManageController::class,'createPlaylist']);
$router->add('POST','/playlists/update',[ManageController::class,'updatePlaylist']);
$router->add('POST','/playlists/delete',[ManageController::class,'deletePlaylist']);
$router->add('POST','/playlists/videos',[ManageController::class,'addPlaylistVideo']);
$router->add('POST','/playlists/videos/delete',[ManageController::class,'removePlaylistVideo']);
$router->add('POST','/playlists/reorder',[ManageController::class,'reorderPlaylist']);
$router->add('GET','/settings',[ManageController::class,'settings']);
$router->add('POST','/settings',[ManageController::class,'saveSettings']);
$router->add('GET','/logs',[ManageController::class,'logs']);
$router->add('POST','/streams/start',[ManageController::class,'start']);
$router->add('POST','/streams/stop',[ManageController::class,'stop']);
$router->add('POST','/streams/restart',[ManageController::class,'restart']);
$router->dispatch();
