<?php declare(strict_types=1);
namespace App\Streaming;
use App\Constants\StreamStatus;use App\Repositories\{ChannelRepository,PlaylistRepository,StreamRepository};use App\Services\{LogService,MediaProbeService,SettingsService,StreamLifecycleService,StreamPreflightService,StreamingProfileService,VideoMetadataService};

final class StreamManager {
    public function __construct(private StreamRepository $streams,private ChannelRepository $channels,private PlaylistRepository $playlists,private SettingsService $settings,private StreamPreflightService $preflight,private StreamLifecycleService $lifecycle,private MediaProbeService $probe,private VideoMetadataService $metadata,private StreamingProfileService $profiles,private LogService $log){}
    public function runPending():void { $stream=$this->streams->active();if(!$stream||($stream['scheduled_start']&&strtotime($stream['scheduled_start'])>time()))return;if($stream['status']===StreamStatus::RUNNING&&$this->exists((int)$stream['pid']))return;$this->run($stream); }
    private function run(array $stream):void { $playlistFile=null;$process=null;try{$channel=$this->channels->find((int)$stream['channel_id']);$videos=$this->playlists->videos((int)$stream['playlist_id']);$settings=$this->settings->all();if(!$channel)throw new \RuntimeException('Channel no longer exists.');$this->preflight->validate($channel,$videos,$settings);$this->log->info('Stream validation successful',['stream_id'=>$stream['id']]);$playlistFile=$this->playlist($stream,$videos);$this->lifecycle->transition($stream,StreamStatus::STARTING,['last_error'=>null]);$stream=$this->streams->find((int)$stream['id']);$attempt=(int)$stream['restart_count'];do{$state=$attempt?StreamStatus::RESTARTING:StreamStatus::RUNNING;if($state===StreamStatus::RESTARTING)$this->lifecycle->transition($stream,$state,['last_restart_at'=>gmdate('Y-m-d H:i:s')]);elseif($stream['status']===StreamStatus::STARTING)$this->lifecycle->transition($stream,$state,['started_at'=>gmdate('Y-m-d H:i:s')]);$stream=$this->streams->find((int)$stream['id']);$process=$this->launch($stream,$channel,$playlistFile,$settings);$exit=$this->wait($process,$stream);$fresh=$this->streams->find((int)$stream['id']);if(($fresh['stop_requested']??false)||$fresh['status']===StreamStatus::STOPPING){$this->lifecycle->transition($fresh,StreamStatus::STOPPED,['pid'=>null,'stopped_at'=>gmdate('Y-m-d H:i:s')]);$this->channels->setStatus((int)$stream['channel_id'],StreamStatus::STOPPED);return;}if($fresh['restart_requested']??false){$attempt=0;$this->streams->update((int)$stream['id'],['restart_requested'=>0,'pid'=>null]);$stream=$this->streams->find((int)$stream['id']);continue;}$attempt++;$reason='FFmpeg exited with code '.$exit;$this->log->error('FFmpeg exited',['stream_id'=>$stream['id'],'exit_code'=>$exit,'restart_count'=>$attempt]);if(($settings['auto_restart']??'1')!=='1'||$attempt>(int)config('stream.max_restarts')){$this->lifecycle->fail($fresh,$reason);$this->channels->setStatus((int)$stream['channel_id'],StreamStatus::FAILED);return;}$this->streams->update((int)$stream['id'],['restart_count'=>$attempt,'pid'=>null,'last_error'=>$reason]);$stream=$this->streams->find((int)$stream['id']);sleep((int)config('stream.restart_delay_seconds'));}while(true);}catch(\Throwable $e){$current=$this->streams->find((int)$stream['id']);if($current&&$current['status']!==StreamStatus::FAILED&&$current['status']!==StreamStatus::STOPPED)$this->lifecycle->fail($current,$e->getMessage());$this->log->error('Stream lifecycle exception',['stream_id'=>$stream['id'],'error'=>$e->getMessage()]);}finally{if(is_resource($process))$this->terminate($process);if($playlistFile&&is_file($playlistFile))unlink($playlistFile);$this->log->info('Stream cleanup completed',['stream_id'=>$stream['id']]);}}
    private function playlist(array $stream,array $videos):string{$file=tempnam(sys_get_temp_dir(),'broadcast-');if($file===false)throw new \RuntimeException('Unable to create playlist file.');$data=implode('',array_map(fn(array $v)=>"file '".str_replace("'","'\\''",config('settings.upload_directory').'/'.$v['filename'])."'\n",$videos));if(file_put_contents($file,$data,LOCK_EX)===false)throw new \RuntimeException('Unable to write playlist file.');$this->log->info('Playlist generated',['stream_id'=>$stream['id'],'videos'=>count($videos)]);return $file;}
    private function launch(array $stream,array $channel,string $playlist,array $settings):mixed{$videos=$this->playlists->videos((int)$stream['playlist_id']);$media=$this->metadata->inspect(config('settings.upload_directory').'/'.$videos[0]['filename']);$profile=$this->profiles->select($media);$command=$this->command($channel,$playlist,$settings,$this->probe->playlistHasAudio($videos),$profile);$this->log->info('FFmpeg command generated',['stream_id'=>$stream['id'],'profile'=>$profile['name'],'input'=>$media,'command'=>$this->masked($command)]);$process=proc_open($command,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($process))throw new \RuntimeException('FFmpeg failed to start.');fclose($pipes[0]);stream_set_blocking($pipes[1],false);stream_set_blocking($pipes[2],false);$status=proc_get_status($process);$this->streams->update((int)$stream['id'],['pid'=>(int)$status['pid']]);$this->channels->setStatus((int)$stream['channel_id'],StreamStatus::RUNNING);$this->log->info('FFmpeg started',['stream_id'=>$stream['id'],'pid'=>$status['pid'],'profile'=>$profile['name']]);return [$process,$pipes];}
    private function wait(array $handle,array $stream):int{[$process,$pipes]=$handle;while(($status=proc_get_status($process))['running']){$this->drain($pipes,$stream);sleep((int)config('stream.poll_seconds'));$fresh=$this->streams->find((int)$stream['id']);if(($fresh['restart_requested']??false)){$this->terminate($handle);break;}if(($fresh['stop_requested']??false)||($fresh['scheduled_end']&&strtotime($fresh['scheduled_end'])<=time())){if($fresh['status']!==StreamStatus::STOPPING)$this->lifecycle->transition($fresh,StreamStatus::STOPPING,['stop_requested'=>1]);$this->terminate($handle);break;}}$this->drain($pipes,$stream);foreach([1,2]as$i)if(is_resource($pipes[$i]))fclose($pipes[$i]);return proc_close($process);}
    private function drain(array $pipes,array $stream):void{foreach([1,2]as$i){$data=stream_get_contents($pipes[$i]);if($data!=='')$this->log->appendStream((int)$stream['id'],$data);}}
    private function terminate(mixed $handle):void{$process=is_array($handle)?$handle[0]:$handle;if(!is_resource($process))return;proc_terminate($process,15);$until=time()+(int)config('stream.terminate_timeout_seconds');while(proc_get_status($process)['running']&&time()<$until)usleep(200000);if(proc_get_status($process)['running'])proc_terminate($process,9);}
    private function command(array $channel,string $playlist,array $settings,bool $hasAudio,array $profile):string{$level=config('app.debug')?config('ffmpeg.developer_loglevel'):config('ffmpeg.production_loglevel');$fps=(int)$profile['fps'];$gop=$fps*(int)config('ffmpeg.keyframe_seconds');$audio=$hasAudio?'-map 0:v:0 -map 0:a?':'-f lavfi -i anullsrc=channel_layout=stereo:sample_rate='.config('ffmpeg.audio_sample_rate').' -map 0:v:0 -map 1:a:0 -shortest';return escapeshellarg($settings['ffmpeg_path']).' -hide_banner -loglevel '.escapeshellarg($level).' -re -stream_loop -1 -f concat -safe 0 -i '.escapeshellarg($playlist).' '.$audio.' -vf '.escapeshellarg('scale='.$profile['resolution']).' -c:v libx264 -pix_fmt yuv420p -preset '.escapeshellarg($profile['preset']).' -r '.$fps.' -g '.$gop.' -keyint_min '.$gop.' -sc_threshold 0 -b:v '.escapeshellarg($profile['bitrate']).' -c:a aac -ar '.config('ffmpeg.audio_sample_rate').' -b:a '.escapeshellarg(config('ffmpeg.audio_bitrate')).' -f flv '.escapeshellarg($channel['rtmp_url'].'/'.$channel['stream_key']);}
    private function masked(string $command):string{return preg_replace("/'[^']*'$/","'[masked]'",$command)??'[masked]';}private function exists(int $pid):bool{return $pid>0&&is_dir('/proc/'.$pid);}
}
