<?php declare(strict_types=1);
namespace App\Streaming;
use App\Constants\StreamStatus;use App\Repositories\{ChannelRepository,PlaylistRepository,StreamRepository};use App\Services\{LogService,MediaProbeService,SettingsService,StreamDiagnosticsService,StreamLifecycleService,StreamPreflightService,StreamingProfileService,VideoMetadataService};
final class StreamManager {
 public function __construct(private StreamRepository $streams,private ChannelRepository $channels,private PlaylistRepository $playlists,private SettingsService $settings,private StreamPreflightService $preflight,private StreamLifecycleService $lifecycle,private MediaProbeService $probe,private VideoMetadataService $metadata,private StreamingProfileService $profiles,private FfmpegCommandBuilder $commands,private StreamDiagnosticsService $diagnostics,private FfmpegSupervisor $supervisor,private LogService $log){}
 public function runPending():void{$stream=$this->streams->active();if(!$stream||($stream['scheduled_start']&&strtotime($stream['scheduled_start'])>time()))return;$this->run($stream);}
 private function run(array $stream):void{$playlist=null;try{$channel=$this->channels->find((int)$stream['channel_id']);$videos=$this->playlists->videos((int)$stream['playlist_id']);$settings=$this->settings->all();if(!$channel)throw new \RuntimeException('Channel no longer exists.');$this->preflight->validate($channel,$videos,$settings);$playlist=$this->playlist($videos);$this->lifecycle->transition($stream,StreamStatus::STARTING,['last_error'=>null]);$attempt=0;do{$fresh=$this->streams->find((int)$stream['id']);$this->lifecycle->transition($fresh,$attempt?StreamStatus::RESTARTING:StreamStatus::RUNNING,['restart_count'=>$attempt,'started_at'=>gmdate('Y-m-d H:i:s')]);$result=$this->supervisor->run($this->command($channel,$videos,$playlist,$settings,$stream),fn(string $out)=>$this->log->appendStream((int)$stream['id'],$out),function()use($stream):bool{$current=$this->streams->find((int)$stream['id']);return (bool)($current['stop_requested']??false)||(bool)($current['restart_requested']??false)||($current['scheduled_end']&&strtotime($current['scheduled_end'])<=time());});$current=$this->streams->find((int)$stream['id']);$this->streams->update((int)$stream['id'],['pid'=>null]);if($current['stop_requested']??false){$this->lifecycle->transition($current,StreamStatus::STOPPED,['stopped_at'=>gmdate('Y-m-d H:i:s')]);return;}if($current['restart_requested']??false){$this->streams->update((int)$stream['id'],['restart_requested'=>0]);$attempt=0;continue;}$attempt++;$reason='FFmpeg exited with code '.$result['exit_code'];$this->log->error('FFmpeg crash',['stream_id'=>$stream['id'],'pid'=>$result['pid'],'exit_code'=>$result['exit_code'],'restart_count'=>$attempt]);if(($settings['auto_restart']??'1')!=='1'||$attempt>(int)config('stream.max_restarts')){$this->lifecycle->fail($current,$reason);return;}sleep((int)config('stream.restart_delay_seconds'));}while(true);}catch(\Throwable $e){$current=$this->streams->find((int)$stream['id']);if($current)$this->lifecycle->fail($current,$e->getMessage());$this->log->error('Stream startup failure',['stream_id'=>$stream['id'],'error'=>$e->getMessage()]);}finally{if($playlist&&is_file($playlist))unlink($playlist);}}
 private function playlist(array $videos):string{$f=tempnam(sys_get_temp_dir(),'broadcast-');file_put_contents($f,implode('',array_map(fn($v)=>"file '".config('settings.upload_directory').'/'.$v['filename']."'\n",$videos)));return $f;}
 private function command(array $channel,array $videos,string $playlist,array $settings,array $stream):string{$metadata=array_map(fn($v)=>$this->metadata->inspect(config('settings.upload_directory').'/'.$v['filename']),$videos);$profile=$this->profiles->selectForPlaylist($metadata);$applied=$this->commands->settings($profile);$this->diagnostics->record((int)$stream['id'],$metadata,$profile,$applied);return $this->commands->build($channel,$playlist,$settings,$this->probe->playlistHasAudio($videos),$profile);}
}
